### PR TITLE
Mahiti 1.5.1 2

### PR DESCRIPTION
**Pull request by kranthi-mahiti**

### CODE REVIEW

**Comment by nehagoel2** [comment]
1. Rename mresp to mResp in Visit Summary screen and follow camel case naming convention. On Vitals activity it has been named as mResp and in Visit Summary as mresp.
2. Respiratory rate does not appear to have been added to the printed prescription - should be added (see screenshot)
whatsapp image 2019-02-20 at 5 22 20 pm

3. Respiratory rate string on the Visit Summary screen Vitals card is just "Respiratory" it should be "Respiratory Rate" or "RR" if there isn't enough screen space - see screenshot.
4. Temperature string on the Vitals card on Visit Summary screen shows Temperature (F) inspite of the temperature being entered in Celcius - see screenshot. The unit should be shown depending on the unit used to enter temperature.
whatsapp image 2019-02-20 at 5 19 30 pm 1



3. Unable to review changes made to client service - git diff does not show specific differences
3,260  app/src/main/java/io/intelehealth/client/services/ClientService.java

**Comment by raunaqp** [comment]
1. There is no unit for each of the vitals in the print function. 
screenshot_2019-02-21-16-55-32-941_com android printspooler

2. In the demo server, the height parameter on the vitals screen is missing! 
screenshot_2019-02-21-16-56-52-474_io intelehealth client

**Comment by kranthi-mahiti** [comment]
@raunaqp  Did you gave the Vitals..?  and Is height is there in Config.json.
I am checking the vitals and everything by config only

**Comment by raunaqp** [comment]
> @raunaqp Did you gave the Vitals..? and Is height is there in Config.json.

The config file has height in it and it is set to be true. But for demo, there is no config file as such. 

> I am checking the vitals and everything by config only

The print option has the temp vitals mentioned in this example, but it doesn't have the unit along with it.

**Comment by kranthi-mahiti** [comment]
@raunaqp @amalafrozalam please merge this to Master branch.

**Pull request merged**
